# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all interceptor options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# 文件的配置选项：https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# 自定义依赖项更新：https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/customizing-dependency-updates
# 管理依赖项更新的所有拉取请求：https://docs.github.com/zh/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
    # https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore
    # 忽略不支持 JDK8 的依赖项
    ignore:
      - dependency-name: org.springframework.boot:spring-boot-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.boot:spring-boot-maven-plugin
        versions:
          - ">= 3"
      - dependency-name: org.springframework.cloud:spring-cloud-dependencies
        versions:
          - ">= 2022"
      - dependency-name: de.codecentric:spring-boot-admin-dependencies
        versions:
          - ">= 3"
      - dependency-name: org.springframework.security:spring-security-oauth2-authorization-server
        versions:
          - ">= 1"
      - dependency-name: com.alibaba.cloud:spring-cloud-alibaba-dependencies
        versions:
          - "= 2021.1"
          - ">= 2022"
      - dependency-name: org.mybatis.spring.boot:mybatis-spring-boot-starter
        versions:
          - ">= 3"
      - dependency-name: org.mybatis:mybatis-spring
        versions:
          - ">= 3"
      - dependency-name: org.springdoc:springdoc-openapi
        versions:
          - ">= 2"
      - dependency-name: mysql:mysql-connector-java
        versions:
          - ">= 8"
      - dependency-name: io.github.git-commit-id:git-commit-id-maven-plugin
        versions:
          - ">= 5"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
