name: Build Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine tag name
        id: tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"

      - name: Build image
        run: |
          docker build -t ${{ github.repository }}:${{ steps.tag.outputs.tag }} .
          docker tag ${{ github.repository }}:${{ steps.tag.outputs.tag }} ${{ github.repository }}:latest

      - name: Push image
        run: docker push ${{ github.repository }}
