# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'Dockerfile'
      - '.dockerignore'
      - 'editorconfig'
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'Dockerfile'
      - '.dockerignore'
      - 'editorconfig'
      - '.github/**'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '1.8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B -U package -P release
