name: Maven Release

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI Skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java Maven Release
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
        with:
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@chensoul.cc"
          release-branch-name: "main"

          maven-args: "-ntp -B -U -P release"
          maven-servers: ${{ secrets.MVN_REPO_SERVERS }}

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: true
          gpg-key-id: ${{ secrets.MAVEN_GPG_ID }}
          gpg-key: ${{ secrets.MAVEN_GPG_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

#      - name: Set up JDK ${{ matrix.Java }}
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: ${{ matrix.java }}
#          cache: maven
#          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
#          server-username: OSSRH_USERNAME
#          server-password: OSSRH_TOKEN
#          gpg-passphrase: MAVEN_GPG_PASSPHRASE
#          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
#
#      - name: Publish to Apache Maven
#        run: mvn -ntp -B -U clean deploy -P release -DskipTests
#        env:
#          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
